### ISSUE TITLE
Interoperability Standards

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#27]
- [x] @maghalandari Send list of interoperability standards to @KonradHoeffner
- [x] @maghalandari Send detailed list of interoperability standards to @KonradHoeffner
- [x] check DBpedia for these interoperability standards, link if possible.
- [x] delete the three subclasses of interoperability standard in the ontology

Table of standards at https://docs.google.com/spreadsheets/d/170b3u_5k3ilvuVnyVFSRY-oN_tD-sY10qzkIRLVBjKU.

Should not be a datatype property but an instance with acronym and full name.

- No distinction between the three classes anymore because assigning standards to these 3 classes is sometimes difficult (although we could do it only if possible, expressing that would be no problem for Linked Data)
- Catalogue from dbpedia - maybe new task: find standards in dbpedia
- AW: problem with IHE (no standard) → FJ: new class for IHE profiles, EA: no, should be easy to use, interoperability standard and convention / agreements?

- AW: HL7 is not a standard.
- EA: We should still include it, as users expect it as a standard in our lists. Change the name to a more generic identifier? E.g. “Interoperatibilitäts-Standards und Konventionen”

**Comment by KonradHoeffner** [comment]
**Interlink Investigation**

The [Object Management Group](https://www.omg.org/) has a lot of RDF resources and seems like a great candidate.

**Comment by ThomasPause** [comment]
dbpedia has a few classes that would partly fit the needs, so we investigated the following:
- 44 resources have an entry in dbpedia
- they are contained in different classes
- a script was written to find the 10 most significant classes
- most of the classes contain too much other objects (often because they are too common)
- results of the script (syntax: Class; number of our resources found, number of instances in class; 

|Class|number of our resources found|number of instances in class|percentage of found to total | 
|---|--------------------------------|---|--------------------------------|
| http://dbpedia.org/class/yago/Abstraction100002137 | 26 | 1079890 | 0.0024076526312865197 |
| http://dbpedia.org/class/yago/Standard107260623 | 20 | 7291 | 0.274310794129749 |
| http://dbpedia.org/class/yago/Measure100033615 | 20 | 84402 | 0.023696120945001304 |
| http://dbpedia.org/class/yago/SystemOfMeasurement113577171 | 20 | 7291 | 0.274310794129749 |
| http://dbpedia.org/class/yago/Communication100033020 | 17 | 171596 | 0.009906990838947295 |
| http://dbpedia.org/class/yago/Message106598915 | 16 | 35659 | 0.04486945792086149 |
| http://dbpedia.org/class/yago/PsychologicalFeature100023100 | 12 | 407890 | 0.0029419696486797913 |
| http://dbpedia.org/class/yago/Information106634376 | 10 | 8069 | 0.12393109431156277 |
| http://dbpedia.org/class/yago/Format106636806 | 10 | 1517 | 0.6591957811470006 |
| http://dbpedia.org/class/yago/WikicatHealthStandards | 9 | 54 | 16.666666666666668 |
| http://dbpedia.org/class/yago/WikicatComputerFileFormats | 9 | 658 | 1.3677811550151975 |

Wikicat Health Standards seems to be the best option so far. 

But to get all the standards we need and not too much around it we will need to model it from the scratch.

**Comment by KonradHoeffner** [comment]
**yago:WikicatHealthStandards**

URI | Label
-- | --
http://dbpedia.org/resource/Healthcare_Services_Specification_Project | Healthcare Services Specification Project
http://dbpedia.org/resource/EN_13606 | EN 13606
http://dbpedia.org/resource/Mirth_Connect | Mirth Connect
http://dbpedia.org/resource/ProRec | ProRec
http://dbpedia.org/resource/General_Data_Format_for_Biomedical_Signals | General Data Format for Biomedical Signals
http://dbpedia.org/resource/Permissible_exposure_limit | Permissible exposure limit
http://dbpedia.org/resource/OpenEHR | OpenEHR
http://dbpedia.org/resource/OBO_Foundry | OBO Foundry
http://dbpedia.org/resource/European_Data_Format | European Data Format
http://dbpedia.org/resource/Nursing_Outcomes_Classification | Nursing Outcomes Classification
http://dbpedia.org/resource/HL7_Services_Aware_Interoperability_Framework | HL7 Services Aware Interoperability Framework
http://dbpedia.org/resource/Recommended_exposure_limit | Recommended exposure limit
http://dbpedia.org/resource/CCOW | CCOW
http://dbpedia.org/resource/NCI_Metathesaurus | NCI Metathesaurus
http://dbpedia.org/resource/Virtual_Medical_Record | Virtual Medical Record
http://dbpedia.org/resource/ICD-10 | ICD-10
http://dbpedia.org/resource/Omaha_System | Omaha System
http://dbpedia.org/resource/Continuity_of_Care_Record | Continuity of Care Record
http://dbpedia.org/resource/Structured_Product_Labeling | Structured Product Labeling
http://dbpedia.org/resource/DICOM | DICOM
http://dbpedia.org/resource/Health_Level_7 | Health Level 7
http://dbpedia.org/resource/Exposure_action_value | Exposure action value
http://dbpedia.org/resource/Electronic_common_technical_document | Electronic common technical document
http://dbpedia.org/resource/British_Pediatric_Association_Classification_of_Diseases | British Pediatric Association Classification of Diseases
http://dbpedia.org/resource/Arden_syntax | Arden syntax
http://dbpedia.org/resource/Clinical_Document_Architecture | Clinical Document Architecture
http://dbpedia.org/resource/Continuity_of_Care_Document | Continuity of Care Document
http://dbpedia.org/resource/Nursing_Interventions_Classification | Nursing Interventions Classification
http://dbpedia.org/resource/SCRIPT_(medicine) | SCRIPT (medicine)
http://dbpedia.org/resource/SNOMED_CT | SNOMED CT
http://dbpedia.org/resource/CEN/TC_251 | CEN/TC 251
http://dbpedia.org/resource/ASC_X12 | ASC X12
http://dbpedia.org/resource/Pathology_Messaging_Implementation_Project | Pathology Messaging Implementation Project
http://dbpedia.org/resource/MedDRA | MedDRA
http://dbpedia.org/resource/ISO/IEEE_11073 | ISO/IEEE 11073
http://dbpedia.org/resource/Healthcare_Information_Technology_Standards_Panel | Healthcare Information Technology Standards Panel
http://dbpedia.org/resource/KMEHR | KMEHR
http://dbpedia.org/resource/HITRUST | HITRUST
http://dbpedia.org/resource/OHSAS_18001 | OHSAS 18001
http://dbpedia.org/resource/XDT | XDT
http://dbpedia.org/resource/Cross_Enterprise_Document_Sharing | Cross Enterprise Document Sharing
http://dbpedia.org/resource/Laika_(EHR_testing_framework) | Laika (EHR testing framework)
http://dbpedia.org/resource/LOINC | LOINC
http://dbpedia.org/resource/Clinical_Data_Interchange_Standards_Consortium | Clinical Data Interchange Standards Consortium
http://dbpedia.org/resource/Standard_for_Exchange_of_Non-clinical_Data | Standard for Exchange of Non-clinical Data
http://dbpedia.org/resource/Systematized_Nomenclature_of_Medicine | Systematized Nomenclature of Medicine
http://dbpedia.org/resource/Read_code | Read code
http://dbpedia.org/resource/Health_Informatics_Service_Architecture | Health Informatics Service Architecture
http://dbpedia.org/resource/BHIE | BHIE
http://dbpedia.org/resource/ELINCS | ELINCS
http://dbpedia.org/resource/SDTM | SDTM
http://dbpedia.org/resource/MECIF_Protocol | MECIF Protocol
http://dbpedia.org/resource/Global_Medical_Device_Nomenclature | Global Medical Device Nomenclature
http://dbpedia.org/resource/Multiscale_Electrophysiology_Format | Multiscale Electrophysiology Format

**Comment by KonradHoeffner** [comment]
The HITO interoperability standard list now been processed and uploaded to the HITO SPARQL endpoint. You can browse it at https://hitontology.eu/ontology/Interoperability (is rdf:type of). External standards lists should still be investigated.

You can also see the new standard instances in the instancegenerator in the form field "interoperability", there should be 106 entries, such as https://hitontology.eu/ontology/ICD10.
